default: &default
  adapter: postgresql

development:
  <<: *default
  database: urban_dev

test:
  <<: *default
  database: urban_test

production:
  <<: *default
  database: urban_prod
  host: localhost
